coralcollector/urls.py
from django.contrib import admin
# Add the include function to the import
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    # include the built-in auth urls for the built-in views
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views
from django.contrib import admin
# Add the include function to the import


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('corals/', views.coral_index, name='index'), 
    path('corals/<int:coral_id>/', views.coral_detail, name='detail'),
    path('corals/create/', views.CoralCreate.as_view(), name='corals_create'),
    path ('corals/<int:pk>/update', views.CoralUpdate.as_view(), name='corals_update'),
    path ('corals/<int:pk>/delete', views.CoralDelete.as_view(), name='corals_delete'),
    path('corals/<int:cat_id>add_feeding/', views.add_feeding, name='add_feeding'),
    
    path('meds/', views.MedsIndex.as_view(), name='med_index'),
    path('meds/create', views.MedsCreate.as_view(), name='med_create'),
    path('meds/<int:pk>/', views.MedsDetail.as_view(), name='med_detail'),
    path('meds/<int:pk>/update', views.MedsUpdate.as_view(), name='med_update'),
    path('meds/<int:pk>/delete', views.MedsDelete.as_view(), name='med_delete'),


    # this path assoiatees meds to a specifc cat
    path('corals/<int:coral_id>/assoc_med/<int:med_id>/',views.assoc_med, name='assoc_med'),

    
    path('accounts/signup/', views.signup, name='signup')

    

]

main_app/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.


class Meds(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    # dunder
    def __str__(self):
        return f'{self.color} {self.name}'

    def get_absolute_url(self):
        return reverse("med_detail", kwargs={"pk": self.id})
    #changed self to .id 
    # we use class based views here thats the onky reasib why pk was used


class Coral (models.Model):
    name = models.CharField(max_length=100)
    species = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    price = models.IntegerField()
# heree is a many to many relationship
    meds = models.ManyToManyField(Meds) 
    # these feidls also correspeond with what is found in the admin login site 
      # Add the foreign key linking to a user instance
    user = models.ForeignKey(User, on_delete=models.CASCADE)
# this str line helps print the text in a better way 
    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse("detail", kwargs={"coral_id": self.id})


class Feeding(models.Model):
    MEALS = (
        ('R', 'ReefRoids'),
        ('A', 'Brightwell Ab+'),
        ('B', 'Benepets'),
    )
    date = models.DateField('feeing date')
    meal = models.CharField(max_length=1, choices=MEALS, default=MEALS[0][0])
    coral = models.ForeignKey(Coral, on_delete=models.CASCADE)
    #cascade means that when corals are deleted so will the model for feeding. 
    # this is similar to embeded relationships
    # this cat right ehre is going to directly reference the one we have above ^^
# dunder method below

    def __str__(self):
        return f'{self.get_meal_display()} on {self.date}'

# feeding needs to be connected to cats. so wht does the feeding need?

# we need a forign key that links the feeding to the model

# below changes the ordering
#here is the link to include specifications on fed corals in the future . 
# https://seir-1114.netlify.app/second-language/week-2/day-3/lecture-materials/intro-to-django-one-to-many-relationships


class meta:
    ordering = ('-date',)

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding


# djandgos form models is designed to make a html5 form from a model
# and thats it

class FeedingForm(ModelForm):
    class Meta:
        # informs the form what model it will be for and what fields we ant inputs for
        model = Feeding
        fields = ('date', 'meal')
        # if we dont specify these two fields it will default to my cat

main_app/views.py
from django.shortcuts import render, redirect

# Add the following import
from django.http import HttpResponse
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import ListView, DetailView
from .models import Coral, Meds, Feeding
from .forms import FeedingForm 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


#botot 3 is for importing photos may need it later 
# import boto3
import uuid


# # Define the home view  
# def home(request):
#     return HttpResponse('<h1>Hello /ᐠ｡‸｡ᐟﾉ</h1>')

def home (request):
    return render(request, "home.html")

def about(request):
    return render(request, 'about.html')


# Add new view
def coral_index(request):
    corals = Coral.objects.all
    return render(request, 'coral/index.html', { 'corals': corals })

#this detail function got updated at the very end in order to show the relationships between the medication  

def coral_detail(request, coral_id):
    corals = Coral.objects.get(id=coral_id)
    feeding_form = FeedingForm()
    meds_not_tried = Meds.objects.exclude(id__in=corals.meds.all().values_list('id'))
    return render(request, 'coral/detail.html',{
        'coral':corals,
        'feeding_form': feeding_form,
        'med': meds_not_tried
#above is returning each model into this function  

        # feeding_formis set to an instance of FeedingFormand then it's passed to detail.html just like coral.
    })
    
def add_feeding(request, coral_id):
    form = FeedingForm(request.POST)
    if form.is_valid():
        new_feeding = form.save(commit = False)
        new_feeding.coral_id = coral_id
        new_feeding.save()
    return redirect('detail', coral_id=coral_id)
    
    # for there to be a relationship between certain things,this must be established 
def assoc_med(request, coral_id,med_id):
  Coral.obejcts.get(id=coral_id).med.add(med_id)
  return redirect('detail', cat_id=med_id)
    
    
def signup(request):
    error_message = 'none'
    # django view functions can hdnle post and get requests
    # the way you check is with an if
    if request.method == 'POST':
        # if get we anna present the user with a signup form and post/ handle a subission fromthe signup from .
        # if not then send a new form to the template

        # capture form inputs from submission
        form = UserCreationForm(request.POST)
        # validate the from inputs
        if form.is_valid():
            # save the new user
            user = form.save()
        # login the new user + redirectino
            login(request, user)
            return redirect('index')
        # if invlaid then error message
    else:
        error_message = 'invalid credentials'

    form = UserCreationForm()
    return render(request, "registration/signup.html", {
        'form': form,
        'error': error_message
    })


    
class CoralCreate(CreateView):
    model = Coral 
    fields = '__all__'
    success_url = '/corals/'

   # this form takes the self anf form
#    renders a form with the users instance from the selfs user request
### this function is for the user auth i believe  
#    def form_valid(self, form):
#        form.instance.user = self.request.user
#        #to hand this back to wehere its pulled you involk super
#        return super().form_valid(form)
       
       

class CoralUpdate(UpdateView):
  model = Coral
  # Let's disallow the renaming of a cat by excluding the name field!
  fields = ['name', 'description', 'species', 'price']

class CoralDelete(DeleteView):
  model = Coral
  success_url = '/corals/'
    
    

#todoo createing a coral landing sppot adn and trying to fix this error markdown is placed where it needs to be. should be bplaced 


class MedsIndex(LoginRequiredMixin, ListView):
  model = Meds


class MedsCreate (LoginRequiredMixin, CreateView):
  model = Meds
  fields = '__all__'


class MedsDetail(LoginRequiredMixin, DetailView):
  model = Meds


class MedsDelete(LoginRequiredMixin, DeleteView):
  model = Meds
  success_url = '/meds/'


class MedsUpdate(LoginRequiredMixin, UpdateView):
  model = Meds
  fields = '__all__'

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Coral Collector</title>
  </head>
  <body>

<h1>About the Coral Collector</h1>
<hr />
<p>I collect corals, and I grow out the rarest ones</p>
<footer>All Rights Reserved, © 2023 Coral Collector</footer>
{% endblock %}
  </body>
</html>

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Coral Collector</title>
    {% comment %} this is the link for materialize  {% endcomment %}
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    {% comment %} in order to make the calender work on the detail page this is requireed {% endcomment %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper  deep-purple accent-1">
          <ul>
            <li>
              <a href="/" class="left brand-logo">  Coral Collector</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="/about">About</a></li>
               {% comment %} {% if user.is_authenticated %} {% endcomment %}
            <li>
              <a href='{% url "med_create" %}'> Add a Medication </a>
            </li>
            <li>
            <a href='{% url "med_index"%}'>View Coral Meds</a>  
            </li>

            <li><a href="{% url 'corals_create' %}">Add a new Coral</a></li>
            <li><a href="/corals">View All My Corals</a></li>
              <li><a href="{% url 'logout' %}">Logout</a></li>
              
              {% comment %} {% else %} {% endcomment %}
             <li><a href="{% url 'login' %}">login</a></li>
              <li><a href="{% url 'signup' %}">Signup</a></li>
              {% comment %} {% endif %} {% endcomment %}

          </ul>
          

        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">
        All Rights Reserved, © 2023 Coral Collector  
      </div>
    </footer>
  </body>
</html>
{% comment %} blocks are used as content setters, essentially i can put anything them like partials and move them around. 
theyre written onthe page like a block so i can be layerd and stacked  
in the about html it has the landing/ extention of this html file. they get added on in a sense . 

{% endcomment %}

main_app/templates/coral/detail.html
{% extends 'base.html' %} {% block content %}
<h1>Coral Details</h1>
<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ coral.name }}</span>
        <p>Species: {{ coral.species }}</p>
        <p>Description: {{ coral.description }}</p>
        {% if coral.price > 200 %}
        <p>Price: {{ coral.price }}</p>
        <p>Sometimes with pricier corals there may be some more research to do before buying</p>
        {% else %}
        <p>Try it out</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'corals_update' coral.id %}">Edit</a>
        <a href="{% url 'corals_delete' coral.id %}">Delete</a> 
      </div>
    </div>
  </div>

  <div class="col s6">
    {% comment %} this is my add to feed button  {% endcomment %}
    {% comment %} this is action attribute form  {% endcomment %}
<form method="post">
    {% csrf_token %} {{ feeding_form.as_p }}
    <input type="submit" class="btn" value="Add Feeding" />
  </form>


    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Meal</th>
        </tr>
      </thead>
      <tbody>
        {% for feeding in coral.feeding_set.all %}
        <tr>
          <td>{{feeding.date}}</td>
          <td>{{feeding.get_meal_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% comment %} need some js in order to make materiaze owrk  

this js also create -the calender  {% endcomment %}
<hr />
{% comment %} this iline of code below will return me the avail meds  {% endcomment %}
<div class="row">
  <div class="col s6">
    <h3>{{ coral.name }}'s Meds</h3>
    {% if coral.meds.count %} {% for med in coral.meds.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          A <span style="color: {{ med.color }}">{{ med.color }}</span> {{
          med.name }}
        </span>
      </div>
    </div>
    {% endfor %} {% else %}
    
    <h5>No Meds :(</h5>
    {% endif %}
  </div>


  </div>
  <!-- Available Medications will come after this line -->
  <div class="col s6">
    <h3>Available Medications</h3>
    {% if meds.count %}
      {% for med in meds.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ meds.color }}">{{ meds.color }}</span> {{ meds.name }}
            </span>
          </div>
          <div class="card-action">
  <form action="{% url 'assoc_med' coral.id med.id %}" method="post">
    {% csrf_token %}
    <button type="submit" class="btn">Add</button>
  </form>
</div>
        </div>
        
      {% endfor %}
    {% else %}
      <h5>{{coral.name}} Already Has All Medications Available</h5>
    {% endif %}
    


  </div>




<script>
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  // add additional JS to initialize select below
  var selectEl = document.getElementById('id_meal');
  M.FormSelect.init(selectEl);
</script>

  



{% endblock %}

main_app/templates/coral/index.html
{%extends 'base.html'%}{%block content%}

<h1>Coral List</h1>

{%for coral in corals%}

<div class="card">
    <a href="{% url 'detail' coral.id %}">
    <span class='card-title'>{{coral.name}}</span>
    <p>Species: {{coral.species}}</p>
    <p>Descriptions: {{ coral.description }}</p>
    {%if coral.species == "euphyllia"%}
    <p>This Coral has a warning for a quick and easy death</p>
    {% else %}
    <p>Pretty Easy, Look for the read me on other species</p>
    <p>Most have the same requirements just need different flow and placement</p>
    {% endif %}

</div>
</a>
</div>


{% endfor %} {% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}


<h1>home </h1>

{% endblock %}

main_app/templates/main_app/coral_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Coral</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' coral.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/coral_form.html
{%extends 'base.html' %} {% block content %}

<form action='' method="POST" autocomplete = 'OFF'>
{% comment %} #actoin tells the from where to  {% endcomment %}

{% csrf_token %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Coral</h1>
{% endif %}

<table>
    {% comment %} this is amodel form this iss  whats generatroed in the views .html 
    the coral update uses teh saem model from as the coral create  {% endcomment %}
    {{form.as_table}}
</table> 

<input type='submit' value='Submit!' class='btn'>
</form>





{% endblock %}

main_app/templates/main_app/meds_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Medication?</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' med.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/meds_detail.html
{%extends "base.html"%}
{% block content %}



<h1>Delete Medication</h1>

<div class='card'>
    <div class="card-content"> 
        <span class = "card-title"> A <span class="{{object.color.lower}}-text"> {{object.color.Capitolize}} </span> {{object.name}} </span>
    </div> 


<div class='card-action'> 
    <a href='{% url "med_update" object.id %}'> Edit </a>

    <a href='{% url "med_update" object.id %}'> Delete </a>
</div>
</div> 

{%endblock%}

main_app/templates/main_app/meds_form.html
{% extends 'base.html' %} {% block content%}


    {% if object %}
<h1>Edit <span class="{{object.color.lower}}-text"> {{object.color.Capitolize}} </span> {{object.name.capitolize}}</h1>
{%else%}
 <h1> Add new Medication </h1> 
    {%endif%}

 <form action="" method="POST">
    {% csrf_token %}
<table> 
    {{form.as_table}}
</table>
<input class="btn green" type="submit" value="submit"> 
 </form> 


{%endblock%}

main_app/templates/main_app/meds_list.html
{% extends "base.html"%}

{% block content %}

<h1> Medication LIst</h1>
{% for med in object_list%}

<a href='{% url "med_detail" med.id%}'> 
    <div class='card'>
        <div class='card-content'> 
            <span class='card-title'> a <span class='{{med.color.lower}}-text'> {{med.color.capitalize}}</span> 
            {{ med.name }} </span
        </div>
    </div>

    {%endfor%}
    {%endblock%}